#!/bin/bash

PAUSECOLOR="#E1A0B8"

STATUS=$(cmus-remote -Q | grep -o -e "status\s.*" | awk -F " " '{print $2}')
META=$(cmus-remote -Q | grep -P -o -e "(?!.*/).*\.mp3" | awk -F "." '{print $1}')

if [[ "${STATUS}" == "paused" ]]; then
	echo "<span foreground='$PAUSECOLOR'>$META</span>"
elif [[ "${STATUS}" == "playing" ]]; then
	echo "$META"
else
	echo ""
fi

case $BLOCK_BUTTON in
	1) cmus-remote -r;;
	2) cmus-remote -u;;
	3) cmus-remote -n;;
esac
